---
title: "Notes"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, messages = TRUE, error = TRUE)
```

## NOTES


```{r}

a <- 1
b <- "hello world" 
d <- "3" #using "" makes it a character instead of number

class(a) #class tells me what kind of variable im working with

class(d)
```

```{r}

vector <- c(1,2,3,4,5,6,7,4,6,7,8,5,3,3,2,8) #vector is what we store 

#process of indentifying whats in a certain spot is indexing. #vector[7] shows us what is in the position 8

vector[2:8] #finds the 2-8 positions

vector [c(10,10,10,10,10,10)] #printing out things in position 10 six times

vector[c(1,2,3,3,2,1)]

vector <- c(1,2,3,4,5,6,7,4,6,7,8,5,3,3,2,8,1000) #note the large inaccuarate number
vector[vector > 7]#only shows numbers that are greater than 7, to elimnate the 1000 insert vector[vector < 7]
vector[vector < 7] #adding >= means greater than or equal to? 
vector[vector == 5] #[==] in a row asks is it equal to?
vector[vector != 5] #[!=] means 

vector [8] <- 2000 #adds a number to the vector position at a later date
vector [1:2] <- 10 #changes first two characters to 10
class(vector) #what is within the vector?

vector[7] <- "j" 
```

```{r}

a <- c("1","2","3") # a is a character vectro with 3 characters in it
class(a) #asks what is in a?
b <- a
class(b)

as.numeric(b) #will try to change the charcters into numbers if they are actually numbers

a <- "iurbgiuqrebguqrvniowenfoimxqwio"
strsplit(a,split="") #use this to split apart character strings
b <- strsplit(a,split="") #
b[[1]][5] #b is a list, access the first list [[1]], turns out the first list is a character vector, [5] access this 5th thing which is a character vector 
class(b)

 #when you have a bunch of strings/variables, write a loop that goes through each string and pulls what you want. vectorized operations does this. if you had paragrahs and you want to see what was in each, strsplit will give you results by each paragraph.

b <- unlist(strsplit(a,split=""))
b[5]

```

```{r}

example_list <- list(a=1, b=4, d=c(1,2,3,4))
example_list[[1]] #[[1]]return whats in list one, used to pull whats from different lists

g <- matrix(0,nrow=5, ncol=3)
View(g)


data.frame() #essentially an excel spreadsheet, if i can get my data into this format all of r will run. 


first_names <- c("asdasas", "fwefef", "sfweg")
ages <- c(2,7,9)
grades <- c(89, 56, 99)

#put into the data frame each variable
everybody <- data.frame(first_names, 
                        ages, 
                        grades)
View(everybody)
everybody$ages[2] #gets the second thing in the column

```
```{r}

a<-"couting the letters in cats and dogs"
table(unlist(strsplit(a,split="")))

#without using table

numbers <- c(1,2,3,4,5)
letters <- c("a","b","c","d","e")

new_df <- data.frame(numbers,letters)#storing variables into data frame 
print(new_df)

new_df$numbers #access individual columns of dataframe

new_df$letters #access individual columns of dataframe

names(new_df) #get names of data.frame




```


##writing function

```{r}

my_function <- function(x){ 
  return(x+1)
} #create fnx to return something #(x)is the input
my_function(2)#(output)

```


```{r}

add_one <- function(x){
  save_result <- x+1
  return()
}


```

```{r}

add_one <- function(x) return(x+1)
add_one
```

##roll dice function
```{r}
sample(1:6,1) #use to get a single random number between 1:6 and 1 number increments

roll_dice <- function(){
  return(sample(1:6,1))
}

roll_dice()#run the fxn with no input

```


###write function to find sum of numbers
```{r, eval=F}
#decalre a fxn
my_numbers <- c(1,4,3,4,5,6) #input will become x variable

my_sum <- function(x){
get_sum <- sum(x) #the sum of x is inside the variable get_sum for storage
return(get_sum) #return will show you what is inside the variable get_sum
}
#print->prints to the console for debugging #return->shows output of fxn
my_sum(1) #my_sum is the fxn #my_numbers is what needs to be done


b <- my_numbers

```



```{r}
some_numbers <- c(3,4,3,2)
ranged_mean2 <- function(x, min_val, max_val){
  restricted_values <- x[x > min_val & x< max_val]
  outputs <- list(original_values = x,
                  restricted_values = restricted_values, #names=data(contents)
                  restricted_mean = mean(restricted_values))#creating restricted values, then placing the mean of those values into it
  return(outputs)
}


```

```{r}
g<-c(-.55,.07,1.95,1.32,.7,1.8,.07,-.55,.07,.07,.7,.07,-2.42,-.55,.7,.07,.07,.07)
hist(g)



```
##histogram with colors and ranges...
```{r}

# Create data for the graph.
v <- c(3, 4, 7, 6, 5, 1, 4, 3, 4, 4, 5, 4, 0, 3, 5, 4, 4, 4)

# Give the chart file a name.
png(file = "histogram_lim_breaks.png")

# Create the histogram.
hist(v,xlab = "Weight",col = "green",border = "red", xlim = c(0,8), ylim = c(0,10),
   breaks = 5)

# Save the file.
dev.off()


```